# Generated by Django 2.2.4 on 2019-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='publication_date',
            field=models.DateField(default=None),
        ),
    ]
